baseURL = 'https://throw.nullreference.io/'
languageCode = 'en-us'
title = "Throwin' Exceptions"
theme = "hugo-theme-bootstrap"
enableGitInfo = true

[frontmatter]
  date = ['date', 'publishDate', 'lastmod', ':fileModTime']
  expiryDate = ['expiryDate']
  lastmod = [':fileModTime', ':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

[build]
  writeStats = true
